# Generated by Django 4.2.5 on 2024-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETMDAPP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField()),
                ("date_of_joining", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_pictures/"
                    ),
                ),
            ],
        ),
    ]
