# Generated by Django 4.2.5 on 2024-04-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETMDAPP", "0005_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="email",
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
