# Generated by Django 4.2.5 on 2024-04-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ETMDAPP", "0007_alter_admin_admin_id_alter_contact_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinishedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("deadline_date", models.DateField()),
                ("deadline_time", models.TimeField()),
                ("email", models.EmailField(max_length=254)),
                ("finished", models.BooleanField(default=False)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ETMDAPP.employee",
                    ),
                ),
            ],
        ),
    ]
