# Generated by Django 4.2.5 on 2024-04-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETMDAPP", "0008_finishedtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="newemail",
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
