# Generated by Django 4.2.5 on 2024-04-28 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ETMDAPP", "0013_employeesignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("Work", "Work"),
                    ("Personal", "Personal"),
                    ("Errands", "Errands"),
                ],
                default="Work",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Medium",
                max_length=10,
            ),
        ),
    ]
