# Generated by Django 4.2.5 on 2024-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETMDAPP", "0014_task_category_task_created_at_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
